### ISSUE TITLE
Scrumblr App Graphics for Sandstorm

### ISSUE THREAD

**Issue by neynah** [ocdtrekkie/scrumblr#5]
Hi @ocdtrekkie 

What do you think about these?

Couldn't really think of many other options so I'm open to suggestions. :)
![scrumblr-preview1](https://cloud.githubusercontent.com/assets/855341/9261335/0559bd80-41c2-11e5-9844-187e4b3b6631.png)

**Comment by ocdtrekkie** [comment]
That seems pretty good. Would you like to submit a pull request to add the files to the repo? Otherwise you can send them to me and I'll add them.

@aliasaria might have thoughts or want to see? (Quick up to speed note if you do: This port is being listed on an 'app market' [for free, credited to you] and it needs some manner of icon-age.)

**Comment by neynah** [comment]
@ocdtrekkie 

I made a slight revision so the app grain icon is more recognizable as a scrumblr icon. Will create a pull request with these shortly.

![scrumblr-preview2](https://cloud.githubusercontent.com/assets/855341/9283409/90606b9c-4288-11e5-9c19-9dc95682dd3b.png)
